version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    expose:
      - "3306"

  streamer:
    build: src/streamer/
    volumes:
      - ./src/streamer:/var/www/html/
      - streamer_videos:/var/www/html/videos/
    environment:
      VIRTUAL_HOST: "${STREAMER_HOSTNAME}"
      VIRTUAL_PORT: 8000
    expose:
      - "8000"
    depends_on:
      - db

  encoder:
    build: src/encoder/
    volumes:
      - ./src/encoder:/var/www/html/
      - encoder_videos:/var/www/html/videos/
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VIRTUAL_HOST: "${ENCODER_HOSTNAME}"
      VIRTUAL_PORT: 8000
    expose:
      - "8000"
    depends_on:
      - db

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - published: 80
        target: 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx-proxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    depends_on:
      - streamer
      - encoder

  coursera:
    build: src/coursera-dl
    volumes:
      - ./downloads/coursera/:/courses

  edx:
    build: src/edx-dl
    volumes:
      - ./downloads/ed-x/:/Downloaded

volumes:
  db_data:
    name: db_data
  encoder_videos:
    name: encoder_videos
  streamer_videos:
    name: streamer_videos
